# Generated by Django 4.2.16 on 2024-09-28 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("vegan", models.BooleanField(default=False)),
                ("vegetarian", models.BooleanField(default=False)),
                ("glutenfree", models.BooleanField(default=False)),
            ],
            options={"ordering": ("name",),},
        ),
        migrations.CreateModel(
            name="Condiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("vegan", models.BooleanField(default=False)),
                ("vegetarian", models.BooleanField(default=False)),
                ("glutenfree", models.BooleanField(default=False)),
            ],
            options={"ordering": ("name",),},
        ),
        migrations.CreateModel(
            name="Hotdog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("vegan", models.BooleanField(default=False)),
                ("vegetarian", models.BooleanField(default=False)),
                ("glutenfree", models.BooleanField(default=False)),
                ("length_cm", models.FloatField(default=15.24)),
            ],
            options={"ordering": ("name",),},
        ),
        migrations.CreateModel(
            name="Topping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("vegan", models.BooleanField(default=False)),
                ("vegetarian", models.BooleanField(default=False)),
                ("glutenfree", models.BooleanField(default=False)),
            ],
            options={"ordering": ("name",),},
        ),
        migrations.CreateModel(
            name="SetMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price_us", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "bun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="menu.bun"
                    ),
                ),
                ("condiments", models.ManyToManyField(blank=True, to="menu.condiment")),
                (
                    "hotdog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="menu.hotdog"
                    ),
                ),
                ("toppings", models.ManyToManyField(blank=True, to="menu.topping")),
            ],
            options={"ordering": ("name",),},
        ),
    ]
